##正式运行时应把开发文档关闭
swagger:
  enabled: true

server:
  port: 8090
  servlet:
    session:
      timeout: PT2H #2H

##db
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    ##数据源其他配置
    druid:
      username: root
      password: 1234567abcd~@A
      url: jdbc:mysql://47.104.191.228:3306/leave?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000                       # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000   # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true  # 配置一个连接在池中最小生存的时间，单位是毫秒

      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        allow: 127.0.0.1

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  redis:
    database: 1
    host: 47.104.191.228
    port: 6379
    password: 1234567abcd~@A
    timeout: 10000 #redis 连接超时时间ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  cache:
    type: redis
    redis:
      time-to-live: 20000 #缓存超时时间ms
      cache-null-values: false #是否缓存空值

  thymeleaf:
    cache: false   #开发时关闭缓存，不然无法看到实时页面

##邮件
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username:
    password:
    protocol: smtp
    test-connection: false
  #    properties:
  #      mail.smtp.auth: true


mybatis:
#  type-aliases-package: com.leave.model
#  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    map-underscore-to-camel-case: true

token:
  expire:
    seconds: 7200
  jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)

files:
  path: ${file-path:d:/files}

##日志
logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/admin-server.log
  maxsize: 30MB