##正式运行时应把开发文档关闭
swagger:
  enabled: true

server:
  port: 8090
  servlet:
    session:
      timeout: PT2H #2H

##db
spring:
  datasource:
    username: root
    password: 1234567abcd~@A
    url: jdbc:mysql://47.104.191.228:3306/leave?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 1
    host: 47.104.191.228
    port: 6379
    password: 1234567abcd~@A
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000 #redis 连接超时时间ms

  cache:
    type: redis
    redis:
      time-to-live: 20000 #缓存超时时间ms
      cache-null-values: false #是否缓存空值

  thymeleaf:
    cache: false   #开发时关闭缓存，不然无法看到实时页面

mybatis:
  configuration:
    map-underscore-to-camel-case: true